parser: babel-eslint
parserOptions:
  ecmaVersion: 7
  ecmaFeatures:
    - jsx: true

plugins:
 - react
 - import
 - jsx-a11y

env:
  browser: true

globals:
  window: true
  require: true
  module: true

rules:
  arrow-spacing:
    - error
    - before: true
      after: true
  block-spacing: error
  brace-style:
    - 2
    - 1tbs
    - allowSingleLine: true
  camelcase:
    - error
    - properties: never
  comma-dangle:
    - error
    - always-multiline
  comma-spacing:
    - error
    - before: false
      after: true
  comma-style:
    - error
    - last
  eol-last: error
  indent:
    - error
    - 2
    - SwitchCase: 1
  key-spacing:
    - error
    - beforeColon: false
      afterColon: true
  keyword-spacing: error
  linebreak-style:
    - error
    - unix
  no-alert: error
  no-console: warn
  no-extra-semi: error
  no-mixed-spaces-and-tabs: error
  no-trailing-spaces: error
  no-unreachable: warn
  no-unused-expressions: warn
  no-unused-vars: warn
  no-var: error
  object-curly-spacing:
    - error
    - always
    - arraysInObjects: false
      objectsInObjects: false
  operator-linebreak:
    - error
    - after
  semi:
    - error
    - always

  react/jsx-uses-react: error
  react/jsx-uses-vars: error
  react/jsx-no-undef: error
  react/react-in-jsx-scope: error

  import/imports-first: error
  import/newline-after-import: error
  import/no-unresolved:
    - error
    - commonjs: true
      amd: true




